jobs:
- job: linux
  container: nventive/wasm-build:1.5

  pool:
    vmImage: 'ubuntu-16.04'

  variables:
    NUGET_PACKAGES: $(build.sourcesdirectory)/.nuget

  steps:
  - checkout: self
    clean: true
  
  - bash: |
      cd ~
      git clone https://github.com/emscripten-core/emsdk
      cd emsdk
      ./emsdk install sdk-1.38.31-64bit
      ./emsdk activate sdk-1.38.31-64bit

    displayName: 'Setup Emscripten'

  - task: GitVersion@5
    inputs:
      useConfigFile: true
      configFilePath: gitversion.yml

  - script: |
      source ~/emsdk/emsdk_env.sh
      cd $(build.sourcesdirectory)
      msbuild /r /p:Configuration=Release $(build.sourcesdirectory)/src/Uno.Playground.WASM/Uno.Playground.WASM.csproj  "/p:InformationalVersion=$GITVERSION_INFORMATIONALVERSION" 

    env:
      GITVERSION_FullSemVer: $(GITVERSION_FullSemVer)
    displayName: 'Build AOT Playground'

  - task: CopyFiles@2
    displayName: 'Publish Wasm Binaries'
    inputs:
      SourceFolder: $(build.sourcesdirectory)/src/Uno.Playground.WASM/bin/Release/netstandard2.0/dist
      Contents: '**/*.*'
      TargetFolder: $(build.artifactstagingdirectory)/Playground-wasm-aot
      CleanTargetFolder: false
      OverWrite: false
      flattenFolders: false

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)
      ArtifactName: Playground-wasm-aot
      ArtifactType: Container
