parameters:
  pool: ''

jobs:
- job: linux

  pool:
    vmImage: 'ubuntu-16.04'

  container: nv-bionic-wasm

  steps:
  - checkout: self
    clean: true
  
  - task: gittools.gitversion.gitversion-task.GitVersion@4
    inputs:
      updateAssemblyInfo: false

  - bash: |
      sudo chmod -R 777 /emsdk
      cd /emsdk
      sudo ./emsdk activate sdk-1.38.28-64bit

    displayName: 'Setup Emscripten'

  - bash: |
      source /emsdk/emsdk_env.sh
      msbuild /r /p:Configuration=Release $(build.sourcesdirectory)/src/Uno.Playground.WASM/Uno.Playground.WASM.csproj

  - task: CopyFiles@2
    inputs:
      SourceFolder: $(build.sourcesdirectory)/src/Uno.Playground.WASM/bin/Release/netstandard2.0/dist
      Contents: "**/*.*"
      TargetFolder: $(build.artifactstagingdirectory)/wasm-aot
      CleanTargetFolder: false
      OverWrite: false
      flattenFolders: false
 
  - task: PublishBuildArtifacts@1
    # https://developercommunity.visualstudio.com/content/problem/284991/public-vsts-previouw-cant-set-build-number-of-pr-b.html
    condition: eq(variables['System.PullRequest.IsFork'], 'False')
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)
      ArtifactName: universal-samples-drop
      ArtifactType: Container
